spring:
  datasource:
    url: jdbc:mysql://192.168.1.6:3306/atsast?useUnicode=true&characterEncoding=UTF-8&serverTimezone=CST&useSSL=false&allowPublicKeyRetrieval=true
    username: atsast
    password: sast_forever
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081
mybatis:
  mapper-locations: classpath:mapper/*.xml
